### ISSUE TITLE
Callback on adjustFocus() ended

### ISSUE THREAD

**Issue by RusinovAnton** [jonom/jquery-focuspoint#53]
Hi, its sad to see when such good project is being forgotten by its maintainer.
However, I'm a believer :)

I want to cloak my image before it adjustment on window load, and for this I need a callback to remove '.loading' class, for example. At this point I'm using next solution
```scss
.focuspoint {
  img {
    opacity: 0;
    transition: opacity .3s;
  }

  img[style] {
    opacity: 1;
  }
}
```

But it seems to be not the best.
I'll add PR on this later. Hope you'll notice it. Bye :)
